Pin the tests to run on ubuntu-2204
ubuntu-latest points to ubuntu-24.04 now. Some python versions were removed
or not included at the moment. An error like this can be found whilst running
in GH without this change:

Version 3.7 was not found in the local cache
  Error: The version '3.7' with architecture 'x64' was not found for Ubuntu 24.04.

Also adding 3.12 to the mix.